import React from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { AIDecision } from '../../types/incident';
import { Bot, ShieldAlert, CheckCircle2, XCircle, Info, Lock } from 'lucide-react';
import { Badge } from '../ui/Badge';

interface AIDecisionPanelProps {
  decision?: AIDecision;
  onApprove: () => void;
  onReject: () => void;
  isPending?: boolean;
}

export const AIDecisionPanel: React.FC<AIDecisionPanelProps> = ({
  decision,
  onApprove,
  onReject,
  isPending = false,
}) => {
  if (!decision) return null;

  return (
    <Card
      title={
        <div className="flex items-center gap-2">
          <Bot className="w-5 h-5 text-indigo-400" />
          <span className="text-base font-bold text-slate-100">AI Decision & Action Proposal</span>
        </div>
      }
      subtitle="Generated by AI Layer 2 Remediation Engine"
      className="border-indigo-500/30 bg-indigo-950/10 shadow-[0_0_24px_rgba(99,102,241,0.08)]"
    >
      <div className="space-y-6">
        {/* Recommended Action Box */}
        <div className="p-4 bg-slate-950/90 border border-slate-800 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <span className="text-xs font-mono text-slate-400 uppercase tracking-wider block">
              Recommended Action
            </span>
            <span className="text-lg font-bold font-mono text-indigo-300 tracking-wide mt-0.5 block">
              {decision.recommended_action}
            </span>
            <span className="text-xs text-slate-400 font-mono mt-1 block">
              Target: <code className="text-slate-200">{decision.target_service}</code>
            </span>
          </div>

          <div className="flex items-center gap-3">
            <div>
              <span className="text-[10px] font-mono text-slate-400 block uppercase">Risk Level</span>
              <Badge variant={decision.risk_level === 'MEDIUM' ? 'warning' : 'critical'} size="sm">
                {decision.risk_level} RISK
              </Badge>
            </div>

            {decision.approval_required && (
              <div className="px-3 py-1.5 rounded-lg bg-amber-950/60 border border-amber-800/60 text-amber-300 font-mono text-xs font-semibold flex items-center gap-1.5">
                <Lock className="w-3.5 h-3.5" /> Human Approval Required
              </div>
            )}
          </div>
        </div>

        {/* Reason */}
        <div className="p-3.5 bg-slate-900/80 border border-slate-800 rounded-xl space-y-1">
          <span className="text-xs font-mono font-semibold text-slate-300 uppercase tracking-wider block">
            AI Action Rationale
          </span>
          <p className="text-xs text-slate-300 leading-relaxed font-sans">{decision.reason}</p>
        </div>

        {/* Human Workflow Action Buttons */}
        <div className="flex flex-wrap items-center justify-end gap-3 pt-2 border-t border-slate-800">
          <Button variant="outline" size="md" onClick={onReject} disabled={isPending} icon={<XCircle className="w-4 h-4" />}>
            Reject
          </Button>
          <Button
            variant="glow"
            size="md"
            onClick={onApprove}
            isLoading={isPending}
            icon={<CheckCircle2 className="w-4 h-4" />}
          >
            Approve Remediation Execution
          </Button>
        </div>
      </div>
    </Card>
  );
};
