"""Add error_code and update IncidentStatus

Revision ID: 4863023ee605
Revises: a9b24fb1bb0a
Create Date: 2026-09-19 01:50:59.549934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4863023ee605'
down_revision: Union[str, Sequence[str], None] = 'a9b24fb1bb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('error_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_error_code'), 'alerts', ['error_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_error_code'), table_name='alerts')
    op.drop_column('alerts', 'error_code')
    # ### end Alembic commands ###
