"""Add NormalizedEvent fields to alerts

Revision ID: a9b24fb1bb0a
Revises: b7c2d91e4a10
Create Date: 2026-09-19 01:26:41.764663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b24fb1bb0a'
down_revision: Union[str, Sequence[str], None] = 'b7c2d91e4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alerts_environment'), 'alerts', ['environment'], unique=False)
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_environment'), table_name='alerts')
    op.drop_column('alerts', 'received_at')
    op.drop_column('alerts', 'environment')
    op.drop_column('alerts', 'event_id')
    # ### end Alembic commands ###
