"""add_knowledge_document

Revision ID: ce207ff6205d
Revises: 4863023ee605
Create Date: 2026-09-19 02:11:38.934517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce207ff6205d'
down_revision: Union[str, Sequence[str], None] = '4863023ee605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_document_type'), 'knowledge_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_environment'), 'knowledge_documents', ['environment'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_error_code'), 'knowledge_documents', ['error_code'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_service'), 'knowledge_documents', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_service'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_error_code'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_environment'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_type'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
